// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZHIy-cgugRKRALnPfdDQYXmzKy9LhpnY',
    appId: '1:236989207257:web:034a28c3c01b0958eba4c8',
    messagingSenderId: '236989207257',
    projectId: 'brew-crew-8f1d0',
    authDomain: 'brew-crew-8f1d0.firebaseapp.com',
    storageBucket: 'brew-crew-8f1d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDytciqrCZvgVGmV1ipJEBEnNDiA8lPSI4',
    appId: '1:236989207257:android:c037492e807fe820eba4c8',
    messagingSenderId: '236989207257',
    projectId: 'brew-crew-8f1d0',
    storageBucket: 'brew-crew-8f1d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHpeSmRGIuBg_cEyVT2RsohSFn4iLrLLA',
    appId: '1:236989207257:ios:5ecb1df42a174c3aeba4c8',
    messagingSenderId: '236989207257',
    projectId: 'brew-crew-8f1d0',
    storageBucket: 'brew-crew-8f1d0.appspot.com',
    iosClientId: '236989207257-8ov2k48la5nt4430tel8tr8dkbij682j.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHpeSmRGIuBg_cEyVT2RsohSFn4iLrLLA',
    appId: '1:236989207257:ios:5ecb1df42a174c3aeba4c8',
    messagingSenderId: '236989207257',
    projectId: 'brew-crew-8f1d0',
    storageBucket: 'brew-crew-8f1d0.appspot.com',
    iosClientId: '236989207257-8ov2k48la5nt4430tel8tr8dkbij682j.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew',
  );
}
